spring:
  application:
    name: microservice-hotel
  datasource:
    url: jdbc:postgresql://database:5432/airline
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  cloud:
    vault:
      host: vault-custom
      port: 8200
      scheme: http
      authentication : TOKEN
      kv:
        backend: kv
        default-context: database
        application-name: database
        enabled: true
  config:
    import: vault://
  flyway:
    locations: classpath:/db/migration

server:
  port: 9002

eureka:
  client:
    fetch-registry: true