CREATE TABLE IF NOT EXISTS entity_hotel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(70),
    stars FLOAT(2) NOT NULL,
    free_rooms INTEGER,
    reserved_rooms INTEGER,
    total_rooms INTEGER,
    contact_phone VARCHAR(15) UNIQUE,
    address_id BIGINT UNIQUE,

    PRIMARY KEY (id)
);
