CREATE TABLE IF NOT EXISTS entity_attraction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    description VARCHAR(255),
    close_at TIME(6),
    open_at TIME(6),
    people_capacity INTEGER NOT NULL,
    hotel_id BIGINT,
    PRIMARY KEY (id)
);

ALTER TABLE entity_attraction DROP CONSTRAINT IF EXISTS hotel_fk;
ALTER TABLE entity_attraction ADD CONSTRAINT hotel_fk FOREIGN KEY (hotel_id) REFERENCES entity_hotel;
