CREATE TABLE IF NOT EXISTS entity_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    description VARCHAR(255),
    open_at TIME(6),
    close_at TIME(6),
    hotel_id BIGINT,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS entity_service DROP CONSTRAINT IF EXISTS hotel_fk;
ALTER TABLE IF EXISTS entity_service ADD CONSTRAINT hotel_fk FOREIGN KEY (hotel_id) REFERENCES entity_hotel;