CREATE TABLE IF NOT EXISTS entity_person (
    age INTEGER NOT NULL,
    number_of_reservations INTEGER NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cell_phone_number VARCHAR(16) UNIQUE,
    dni VARCHAR(10) UNIQUE,
    email VARCHAR(30) UNIQUE,
    name VARCHAR(50),
    address_id BIGINT UNIQUE,
    PRIMARY KEY (id)
);

