CREATE TABLE IF NOT EXISTS entity_room (
    floor INTEGER NOT NULL,
    number_of_beds INTEGER NOT NULL,
    people_capacity INTEGER NOT NULL,
    price_per_night NUMERIC(38,2),
    hotel_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    times_booked BIGINT,
    bed_type VARCHAR(16) CHECK (
        bed_type IN ('SINGLE_BED','DOUBLE_BED','QUEEN_BED','KING_BED','TWIN_BED')
        ),
    room_type VARCHAR(16) CHECK (
        room_type IN ('STANDARD','DELUXE','SUITE','EXECUTIVE','PRESIDENTIAL')
        ),
    state VARCHAR(16) CHECK (
        state IN ('OCCUPIED','UNOCCUPIED','BEING_CLEANED','CLEANED','FREE','RESERVED')
        ),
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS entity_room DROP CONSTRAINT IF EXISTS hotel_fk;
ALTER TABLE IF EXISTS entity_room ADD CONSTRAINT hotel_fk FOREIGN KEY (hotel_id) REFERENCES entity_hotel;