CREATE TABLE IF NOT EXISTS entity_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    end_at DATE,
    start_at DATE,
    total_price NUMERIC(38,2),
    number_of_nights BIGINT,
    number_of_people BIGINT,
    room_id BIGINT,
    person_id BIGINT UNIQUE,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS entity_reservation DROP CONSTRAINT IF EXISTS person_fk;
ALTER TABLE IF EXISTS entity_reservation DROP CONSTRAINT IF EXISTS room_fk;
ALTER TABLE IF EXISTS entity_reservation ADD CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES entity_person;
ALTER TABLE IF EXISTS entity_reservation ADD CONSTRAINT room_fk FOREIGN KEY (room_id) REFERENCES entity_room;