CREATE TABLE IF NOT EXISTS entity_room_booking_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    end_at DATE,
    start_at DATE,
    status VARCHAR(16) CHECK (
        status IN ('RESERVED','CANCELLED','COMPLETED','BLOCKED')
        ),
    reservation_id BIGINT UNIQUE,
    room_id BIGINT,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS entity_room_booking_period DROP CONSTRAINT IF EXISTS reservation_fk;
ALTER TABLE IF EXISTS entity_room_booking_period DROP CONSTRAINT IF EXISTS room_fk;
ALTER TABLE IF EXISTS entity_room_booking_period ADD CONSTRAINT reservation_fk FOREIGN KEY (reservation_id) REFERENCES entity_reservation;
ALTER TABLE IF EXISTS entity_room_booking_period ADD CONSTRAINT room_fk FOREIGN KEY (room_id) REFERENCES entity_room;