CREATE TABLE IF NOT EXISTS entity_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country_code VARCHAR(50) NOT NULL,
    subdivision_name VARCHAR(70) NOT NULL,
    code VARCHAR(6) NOT NULL,
    PRIMARY KEY (id)
);

COPY entity_states (country_code, subdivision_name, code)
FROM '/countries_csv/states.CSV'
WITH (FORMAT csv, HEADER true);

ALTER TABLE entity_states ADD CONSTRAINT countries_fk FOREIGN KEY (country_code) REFERENCES entity_country;