CREATE TABLE IF NOT EXISTS entity_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    street VARCHAR(50) NOT NULL,
    number VARCHAR(10) NOT NULL,
    floor BIGINT,
    department_number BIGINT,
    state_code varchar(6),
    PRIMARY KEY (id)
);

ALTER TABLE entity_address DROP CONSTRAINT IF EXISTS states_fk;
ALTER TABLE entity_hotel DROP CONSTRAINT IF EXISTS hotel_address_fk;
ALTER TABLE entity_person DROP CONSTRAINT IF EXISTS person_address_fk;
ALTER TABLE entity_address ADD CONSTRAINT states_fk FOREIGN KEY (id) REFERENCES entity_states;
ALTER TABLE entity_hotel ADD CONSTRAINT hotel_address_fk FOREIGN KEY (address_id) REFERENCES entity_address;
ALTER TABLE entity_person ADD CONSTRAINT person_address_fk FOREIGN KEY (address_id) REFERENCES entity_address;